#!/bin/sh

PRESETS='./dotfiles/presets'

copy() {
	cp -rfvT "$1" "$2"
}

selected_preset="$1"

if [ -z "$selected_preset" ]
then
	exit 0
fi

if [ ! -f "$PRESETS/$selected_preset" ]
then
	printf 'Dotfiles preset %s not found\n' "$selected_preset"

	exit 1
fi

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"

cd ./dotfiles
. "./presets/$selected_preset"
