#!/bin/sh

PRESETS='./dotfiles/presets'

copy() {
	cp -rfvT "$1" "$2"
}

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"

printf 'Available dotfiles presets:\n'
ls -1 "$PRESETS"
printf 'Dotfiles preset to use or empty to exit: '
read -r selected_preset

if [ -z "$selected_preset" ]
then
	exit 0
fi

if [ ! -f "$PRESETS/$selected_preset" ]
then
	printf 'Dotfiles preset %s not found\n' "$selected_preset"

	exit 1
fi

cd ./dotfiles
. "./presets/$selected_preset"
