#!/bin/sh

PRESETS='./install/presets'

selected_preset="$1"

if [ -z "$selected_preset" ]
then
	exit 0
fi

if [ ! -f "$PRESETS/$selected_preset" ]
then
	printf 'Install preset %s not found\n' "$selected_preset"

	exit 1
fi

cd './install'
. "./presets/$selected_preset"
