#!/bin/sh

pacman -Qi paru > /dev/null 2>&1

if [ $? = 1 ]
then
	sudo pacman -S --needed base-devel

	git clone --depth 1 https://aur.archlinux.org/paru.git paru
	cd paru || exit 1

	makepkg -si || exit 1
	paru --gendb

	cd ..

	rm -rf paru
fi

exit 0
